In [16]:
import pandas as pd
import numpy as np

In [2]:
from pandas import Series,DataFrame

In [3]:
obj = pd.Series([4,7,-5,3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4,-7,-5,3],index=['d','b','a','c'])

In [8]:
obj2

d    4
b   -7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

-5

In [12]:
obj2[['c','a','d']]

c    3
a   -5
d    4
dtype: int64

In [13]:
obj2[obj2 > 0]

d    4
c    3
dtype: int64

In [14]:
obj2*2

d     8
b   -14
a   -10
c     6
dtype: int64

In [17]:
np.exp(obj2)

d    54.598150
b     0.000912
a     0.006738
c    20.085537
dtype: float64

In [18]:
'b'in obj2

True

In [19]:
'e'in obj2

False

In [20]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [21]:
obj3 = pd.Series(sdata)

In [22]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [23]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [24]:
obj4 = pd.Series(sdata,index=states)

In [25]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [27]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [29]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [30]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [31]:
obj3  + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [33]:
obj4.name = 'population'

In [34]:
obj4.index.name = 'state'

In [35]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [36]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [37]:
obj.index = ['Bob','Steve','Jeff','Ryan']

In [38]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [39]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [40]:
frame = pd.DataFrame(data)

In [41]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [44]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [45]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [46]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five', 'six'])

In [47]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [48]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [49]:
frame['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [50]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [51]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [52]:
frame2['debt'] = 16.5

In [53]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [58]:
frame2['debt'] = np.arange(6.)

In [59]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [60]:
va1 = pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [62]:
frame2['debt'] = va1

In [63]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [64]:
frame2['eastern'] = frame2.state == 'Ohio'

In [66]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [67]:
del frame2['eastern']

In [68]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [69]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [80]:
 pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 
        'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [81]:
frame3 = pd.DataFrame(pop)

In [73]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [74]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [84]:
pd.DataFrame(pop,index=pd.Series([2001,2002,2003]))

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [85]:
 pdata = {'Ohio': frame3['Ohio'][:-1],
          'Nevada': frame3['Nevada'][:2]}

In [86]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [87]:
frame3.index.name = 'year';frame3.columns.name = 'state'

In [88]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [89]:
frame3.index

Int64Index([2000, 2001, 2002], dtype='int64', name='year')

In [90]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [91]:
obj = pd.Series(range(3),index=['a','b','c'])

In [92]:
index = obj.index

In [93]:
index

Index(['a', 'b', 'c'], dtype='object')

In [94]:
index[:1]

Index(['a'], dtype='object')

In [97]:
index[0] = "c"

TypeError: Index does not support mutable operations

In [100]:
labels = pd.Index(np.arange(3))

In [101]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [102]:
obj2 = pd.Series([1.5,-2.5,0],index=labels)

In [103]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [104]:
obj2.index is labels

True

In [105]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [106]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [107]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [108]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [109]:
obj = pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])

In [110]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [111]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [113]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [114]:
obj3 = pd.Series(['blue','purple','yellow'],index=[0,2,4])

In [115]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [116]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [117]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index=['a','c','d'],
                    columns=['Ohio','Texax','California'])

In [118]:
frame

Ohio  Texax  California
a     0      1           2
c     3      4           5
d     6      7           8

In [119]:
frame2 = frame.reindex(['a','b','c','d'])

In [120]:
frame2

Ohio  Texax  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [121]:
states = ['Texas','Utah','California']

In [122]:
frame.reindex(columns=states)

Texas  Utah  California
a    NaN   NaN           2
c    NaN   NaN           5
d    NaN   NaN           8

In [123]:
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])

In [124]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [125]:
new_obj = obj.drop('c')

In [126]:
new_obj 

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [127]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [128]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),                   
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [129]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [130]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [135]:
data.drop('Utah')

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York   12   13     14    15

In [139]:
obj = pd.Series(np.arange(4.),index=['a','b','c','d'])

In [137]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [140]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [141]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [142]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [143]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [144]:
obj['b':'c'] = 5

In [145]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [146]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [147]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [148]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [149]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [150]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [151]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [152]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [153]:
data[data < 5] = 0

In [154]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [155]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [156]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [157]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [158]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [159]:
data.iloc[:,:3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [162]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [164]:
ser2 = pd.Series(np.arange(3.),index=['a','b','c'])

In [165]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [167]:
ser2[-1]

2.0

In [168]:
ser[:1]

0    0.0
dtype: float64

In [169]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [170]:
ser.iloc[:1]

0    0.0
dtype: float64

In [172]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])

In [173]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [174]:
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],
              index=['a','c','e','f','g'])

In [175]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [176]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [177]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])

In [178]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [179]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [180]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [181]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [182]:
df1 = pd.DataFrame({'A':[1,2]})

In [183]:
df2 = pd.DataFrame({'B':[3,4]})

In [184]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                  columns=list('abcd'))

In [185]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [186]:
 df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                    columns=list('abcde'))

In [187]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [188]:
df2.loc[1,'b'] = np.nan

In [189]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [190]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [191]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [192]:
1/df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [193]:
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [194]:
arr = np.arange(12.).reshape((3,4))

In [195]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [196]:
arr[0]

array([0., 1., 2., 3.])

In [197]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [199]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [200]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [202]:
series = frame.iloc[0]

In [203]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [204]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [205]:
series2 = pd.Series(range(3),index=['b','e','f'])

In [207]:
series2

b    0
e    1
f    2
dtype: int64

In [208]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [209]:
series3 = frame['d']

In [210]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [211]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [212]:
frame.sub(series3,axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [213]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [214]:
frame

b         d         e
Utah   -0.757727  1.698078 -1.362334
Ohio   -0.392222  1.380093 -0.549550
Texas  -2.407430  0.094908 -1.031633
Oregon  1.501761  0.152255 -0.609533

In [215]:
np.abs(frame)

b         d         e
Utah    0.757727  1.698078  1.362334
Ohio    0.392222  1.380093  0.549550
Texas   2.407430  0.094908  1.031633
Oregon  1.501761  0.152255  0.609533

In [216]:
f = lambda x:x.max() - x.min()

In [217]:
frame.apply(f)

b    3.909192
d    1.603170
e    0.812784
dtype: float64

In [218]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])

In [219]:
frame.apply(f)

b         d         e
min -2.407430  0.094908 -1.362334
max  1.501761  1.698078 -0.549550

In [220]:
format = lambda x:'%.2f'% x

In [221]:
frame.applymap(format)

b     d      e
Utah    -0.76  1.70  -1.36
Ohio    -0.39  1.38  -0.55
Texas   -2.41  0.09  -1.03
Oregon   1.50  0.15  -0.61

In [222]:
frame['e'].map(format)

Utah      -1.36
Ohio      -0.55
Texas     -1.03
Oregon    -0.61
Name: e, dtype: object

In [223]:
obj = pd.Series(range(4),index=['d','a','b','c'])

In [224]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [228]:
obj.sort_index()


a    1
b    2
c    3
d    0
dtype: int64

In [229]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])

In [230]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [231]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [232]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [233]:
obj = pd.Series([4,7,-3,2])

In [235]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [236]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [237]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [238]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [242]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [243]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [246]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [245]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [247]:
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [248]:
obj = pd.Series(range(5),index=['a','a','b','b','c'])

In [249]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [250]:
obj.index.is_unique

False

In [251]:
obj['a']

a    0
a    1
dtype: int64

In [252]:
obj['c']

4

In [253]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [254]:
df

0         1         2
a -0.086431  0.671644  1.563163
a  1.617258  0.434034 -1.061300
b  0.554228  0.756268 -0.277368
b -2.653578  0.080042  1.237232

In [255]:
df.loc['b']

0         1         2
b  0.554228  0.756268 -0.277368
b -2.653578  0.080042  1.237232

In [256]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                  [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])

In [257]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [258]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [259]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [262]:
df.idxmax()

one    b
two    d
dtype: object

In [264]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [265]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [266]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [267]:
obj = pd.Series(['a','a','b','c'] * 4)

In [268]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [269]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [270]:
import pandas_datareader.data as web

In [271]:
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [272]:
all_data

{'AAPL':                   High         Low        Open       Close       Volume  \
 Date                                                                      
 2009-12-31   30.478571   30.080000   30.447144   30.104286   88102700.0   
 2010-01-04   30.642857   30.340000   30.490000   30.572857  123432400.0   
 2010-01-05   30.798571   30.464285   30.657143   30.625713  150476200.0   
 2010-01-06   30.747143   30.107143   30.625713   30.138571  138040000.0   
 2010-01-07   30.285715   29.864286   30.250000   30.082857  119282800.0   
 2010-01-08   30.285715   29.865715   30.042856   30.282858  111902700.0   
 2010-01-11   30.428572   29.778572   30.400000   30.015715  115557400.0   
 2010-01-12   29.967142   29.488571   29.884285   29.674286  148614900.0   
 2010-01-13   30.132856   29.157143   29.695715   30.092857  151473000.0   
 2010-01-14   30.065714   29.860001   30.015715   29.918571  108223500.0   
 2010-01-15   30.228571   29.410000   30.132856   29.418571  148516900.0   
 201

In [273]:
returns = price.pct_change()

In [275]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2019-05-06 -0.015443  0.000927 -0.005818  0.003366
2019-05-07 -0.026957 -0.019518 -0.020523 -0.012855
2019-05-08  0.000197  0.002616 -0.000080 -0.006669
2019-05-09 -0.010744 -0.007626 -0.000080 -0.003335
2019-05-10 -0.013853 -0.000148  0.012988  0.001626

In [277]:
returns['MSFT'].corr(returns['IBM'])

0.48565223570590677

In [278]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.370686  0.448227  0.455828
IBM   0.370686  1.000000  0.485652  0.403451
MSFT  0.448227  0.485652  1.000000  0.534356
GOOG  0.455828  0.403451  0.534356  1.000000

In [279]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000269  0.000075  0.000106  0.000115
IBM   0.000075  0.000151  0.000086  0.000077
MSFT  0.000106  0.000086  0.000209  0.000119
GOOG  0.000115  0.000077  0.000119  0.000238

In [280]:
returns.corrwith(returns.IBM)

AAPL    0.370686
IBM     1.000000
MSFT    0.485652
GOOG    0.403451
dtype: float64

In [281]:
returns.corrwith(volume)

AAPL   -0.060065
IBM    -0.155818
MSFT   -0.089679
GOOG   -0.020541
dtype: float64

In [282]:
obj = pd.Series(['c','a','d','a','a','b','b','c','c'])

In [283]:
uniques = obj.unique()

In [284]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [285]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [289]:
pd.value_counts(obj.values,sort=False)

d    1
c    3
b    2
a    3
dtype: int64

In [290]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [291]:
mask = obj.isin(['b','c'])

In [292]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [293]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [294]:
to_math = pd.Series(['c','a','b','b','c','a'])

In [296]:
unique_vals = pd.Series(['c','b','a'])

In [301]:
pd.Index(unique_vals).get_indexer(to_math)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [302]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})

In [303]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [304]:
result = data.apply(pd.value_counts).fillna(0)

In [305]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0