In [1]:
import numpy as np
import pandas as pd

In [2]:
values = pd.Series(['apple','orange','apple','apple']*2)

In [3]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [4]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [5]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [6]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [7]:
values = pd.Series(['apple','orange'])

In [8]:
values

0     apple
1    orange
dtype: object

In [10]:
values = pd.Series([0,1,0,0]*2)

In [11]:
dim = pd.Series(['apple','orange'])

In [12]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [13]:
dim

0     apple
1    orange
dtype: object

In [14]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [15]:
fruits = ['apple','orange','apple','apple']*2

In [16]:
N = len(fruits)

In [17]:
df = pd.DataFrame({'fruit': fruits,
   ....:           'basket_id': np.arange(N),
   ....:           'count': np.random.randint(3, 15, size=N),
   ....:           'weight': np.random.uniform(0, 4, size=N)},
   ....:           columns=['basket_id', 'fruit', 'count', 'weight'])

In [18]:
df

basket_id   fruit  count    weight
0          0   apple     14  2.174596
1          1  orange      6  2.584682
2          2   apple     11  3.550655
3          3   apple     11  0.192601
4          4   apple     12  2.735451
5          5  orange     11  0.573315
6          6   apple     14  1.722071
7          7   apple     13  0.441595

In [19]:
fruit_cat = df['fruit'].astype('category')

In [20]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): [apple, orange]

In [21]:
c = fruit_cat.values

In [22]:
type(c)

pandas.core.arrays.categorical.Categorical

In [23]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [24]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [25]:
df['fruit'] = df['fruit'].astype('category')

In [26]:
df.fruit

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): [apple, orange]

In [27]:
my_categories = pd.Categorical(['foo','bar','baz','foo','bar'])

In [28]:
my_categories

[foo, bar, baz, foo, bar]
Categories (3, object): [bar, baz, foo]

In [29]:
categories = ['foo','bar','baz']

In [30]:
codes = [0,1,2,0,0,1]

In [31]:
my_cats_2 = pd.Categorical.from_codes(codes,categories)

In [33]:
my_cats_2

[foo, bar, baz, foo, foo, bar]
Categories (3, object): [foo, bar, baz]

In [34]:
ordered_cat = pd.Categorical.from_codes(codes,categories,ordered=True)

In [35]:
ordered_cat

[foo, bar, baz, foo, foo, bar]
Categories (3, object): [foo < bar < baz]

In [36]:
my_cats_2.as_ordered()

[foo, bar, baz, foo, foo, bar]
Categories (3, object): [foo < bar < baz]

In [37]:
np.random.seed(12345)

In [38]:
draws = np.random.randn(1000)

In [39]:
draws[:5]

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057])

In [40]:
bins = pd.qcut(draws,4)

In [41]:
bins

[(-0.684, -0.0101], (-0.0101, 0.63], (-0.684, -0.0101], (-0.684, -0.0101], (0.63, 3.928], ..., (-0.0101, 0.63], (-0.684, -0.0101], (-2.9499999999999997, -0.684], (-0.0101, 0.63], (0.63, 3.928]]
Length: 1000
Categories (4, interval[float64]): [(-2.9499999999999997, -0.684] < (-0.684, -0.0101] < (-0.0101, 0.63] < (0.63, 3.928]]

In [42]:
bins = pd.qcut(draws,4,labels=['Q1','Q2','Q3','Q4'])

In [43]:
bins

[Q2, Q3, Q2, Q2, Q4, ..., Q3, Q2, Q1, Q3, Q4]
Length: 1000
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [44]:
bins.codes[:10]

array([1, 2, 1, 1, 3, 3, 2, 2, 3, 3], dtype=int8)

In [45]:
bins = pd.Series(bins,name='quartile')

In [46]:
results = (pd.Series(draws).groupby(bins).agg(['count','min','max']).reset_index())

In [47]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [48]:
N = 10000000

In [49]:
draws = pd.Series(np.random.randn(N))

In [50]:
labels = pd.Series(['foo','bar','baz','qux']*(N//4))

In [51]:
categories = labels.astype('category')

In [52]:
labels.memory_usage()

80000080

In [54]:
categories.memory_usage()

10000272

In [57]:
%time _ = labels.astype('category')

Wall time: 332 ms


In [58]:
%time _ = labels.memory_usage()

Wall time: 2.99 ms


In [59]:
s = pd.Series(['a','b','c','d']*2) 

In [60]:
s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: object

In [61]:
cat_s = s.astype('category')

In [62]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): [a, b, c, d]

In [63]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [65]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [66]:
actual_categories = ['a','b','c','d','e']

In [67]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [68]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): [a, b, c, d, e]

In [69]:
cat_s.value_counts()

d    2
c    2
b    2
a    2
dtype: int64

In [70]:
cat_s2.value_counts()

d    2
c    2
b    2
a    2
e    0
dtype: int64

In [72]:
cat_s3 = cat_s[cat_s.isin(['a','b'])]

In [73]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): [a, b, c, d]

In [74]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): [a, b]

In [75]:
cat_s = pd.Series(['a','b','c','d']*2,dtype='category')

In [76]:
pd.get_dummies(cat_s)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1

In [77]:
df = pd.DataFrame({'key':['a','b','c']*4,
                  'value':np.arange(12.)})

In [78]:
df

key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [79]:
g = df.groupby('key').value

In [80]:
g.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [81]:
g.transform(lambda x:x.mean())

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [82]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [83]:
g.transform(lambda x:x*2)

0      0.0
1      2.0
2      4.0
3      6.0
4      8.0
5     10.0
6     12.0
7     14.0
8     16.0
9     18.0
10    20.0
11    22.0
Name: value, dtype: float64

In [84]:
g.transform(lambda x:x.rank(ascending=False))

0     4.0
1     4.0
2     4.0
3     3.0
4     3.0
5     3.0
6     2.0
7     2.0
8     2.0
9     1.0
10    1.0
11    1.0
Name: value, dtype: float64

In [85]:
def normalize(x):
    return (x-x.mean()) / x.std()

In [86]:
g.transform(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [87]:
g.apply(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [88]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [90]:
noramlized = (df['value']-g.transform('mean'))/g.transform('std')

In [92]:
noramlized

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [93]:
N = 15 

In [95]:
times = pd.date_range('2019-5-20 00:00',freq='1min',periods=N)

In [96]:
df = pd.DataFrame({'time':times,
                  'value':np.arange(N)})

In [97]:
df

time  value
0  2019-05-20 00:00:00      0
1  2019-05-20 00:01:00      1
2  2019-05-20 00:02:00      2
3  2019-05-20 00:03:00      3
4  2019-05-20 00:04:00      4
5  2019-05-20 00:05:00      5
6  2019-05-20 00:06:00      6
7  2019-05-20 00:07:00      7
8  2019-05-20 00:08:00      8
9  2019-05-20 00:09:00      9
10 2019-05-20 00:10:00     10
11 2019-05-20 00:11:00     11
12 2019-05-20 00:12:00     12
13 2019-05-20 00:13:00     13
14 2019-05-20 00:14:00     14

In [98]:
df.set_index('time').resample('5min').count()

value
time                      
2019-05-20 00:00:00      5
2019-05-20 00:05:00      5
2019-05-20 00:10:00      5

In [99]:
df2 = pd.DataFrame({'time': times.repeat(3),
                    'key': np.tile(['a', 'b', 'c'], N),
                    'value': np.arange(N * 3.)})

In [100]:
df2

time key  value
0  2019-05-20 00:00:00   a    0.0
1  2019-05-20 00:00:00   b    1.0
2  2019-05-20 00:00:00   c    2.0
3  2019-05-20 00:01:00   a    3.0
4  2019-05-20 00:01:00   b    4.0
5  2019-05-20 00:01:00   c    5.0
6  2019-05-20 00:02:00   a    6.0
7  2019-05-20 00:02:00   b    7.0
8  2019-05-20 00:02:00   c    8.0
9  2019-05-20 00:03:00   a    9.0
10 2019-05-20 00:03:00   b   10.0
11 2019-05-20 00:03:00   c   11.0
12 2019-05-20 00:04:00   a   12.0
13 2019-05-20 00:04:00   b   13.0
14 2019-05-20 00:04:00   c   14.0
15 2019-05-20 00:05:00   a   15.0
16 2019-05-20 00:05:00   b   16.0
17 2019-05-20 00:05:00   c   17.0
18 2019-05-20 00:06:00   a   18.0
19 2019-05-20 00:06:00   b   19.0
20 2019-05-20 00:06:00   c   20.0
21 2019-05-20 00:07:00   a   21.0
22 2019-05-20 00:07:00   b   22.0
23 2019-05-20 00:07:00   c   23.0
24 2019-05-20 00:08:00   a   24.0
25 2019-05-20 00:08:00   b   25.0
26 2019-05-20 00:08:00   c   26.0
27 2019-05-20 00:09:00   a   27.0
28 2019-05-20 00:09:00   b   28.0
29 2019-05-20 00:09:00   c   29.0
30 2019-05-20 00:10:00   a   30.0
31 2019-05-20 00:10:00   b   31.0
32 2019-05-20 00:10:00   c   32.0
33 2019-05-20 00:11:00   a   33.0
34 2019-05-20 00:11:00   b   34.0
35 2019-05-20 00:11:00   c   35.0
36 2019-05-20 00:12:00   a   36.0
37 2019-05-20 00:12:00   b   37.0
38 2019-05-20 00:12:00   c   38.0
39 2019-05-20 00:13:00   a   39.0
40 2019-05-20 00:13:00   b   40.0
41 2019-05-20 00:13:00   c   41.0
42 2019-05-20 00:14:00   a   42.0
43 2019-05-20 00:14:00   b   43.0
44 2019-05-20 00:14:00   c   44.0

In [101]:
time_key = pd.TimeGrouper('5min')

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: pd.TimeGrouper is deprecated and will be removed; Please use pd.Grouper(freq=...)
  """Entry point for launching an IPython kernel.


In [102]:
resample = (df2.set_index('time').groupby(['key',time_key])
           .sum())

In [104]:
resample

value
key time                      
a   2019-05-20 00:00:00   30.0
    2019-05-20 00:05:00  105.0
    2019-05-20 00:10:00  180.0
b   2019-05-20 00:00:00   35.0
    2019-05-20 00:05:00  110.0
    2019-05-20 00:10:00  185.0
c   2019-05-20 00:00:00   40.0
    2019-05-20 00:05:00  115.0
    2019-05-20 00:10:00  190.0

In [105]:
resample.reset_index()

key                time  value
0   a 2019-05-20 00:00:00   30.0
1   a 2019-05-20 00:05:00  105.0
2   a 2019-05-20 00:10:00  180.0
3   b 2019-05-20 00:00:00   35.0
4   b 2019-05-20 00:05:00  110.0
5   b 2019-05-20 00:10:00  185.0
6   c 2019-05-20 00:00:00   40.0
7   c 2019-05-20 00:05:00  115.0
8   c 2019-05-20 00:10:00  190.0

In [106]:
df = load_data()
df2 = df[df['col2'] < 0]
df2['col1_demeaned'] = df2['col1'] - df2['col1'].mean()
result = df2.groupby('key').col1_demeaned.std()

NameError: name 'load_data' is not defined